// env vars
process.env.NODE_ENV = 'test'
process.env.NEXMO_API_KEY = 'NEXMO_API_KEY'
process.env.NEXMO_API_SECRET = 'NEXMO_API_SECRET'
process.env.FIREBASE_DB_URL = ''
process.env.FIREBASE_ACCOUNT_KEY = ''
process.env.FIREBASE_ACCOUNT_KEY_type = ''
process.env.FIREBASE_ACCOUNT_KEY_project_id = ''
process.env.FIREBASE_ACCOUNT_KEY_private_key_id = ''
process.env.FIREBASE_ACCOUNT_KEY_private_key = ''
process.env.FIREBASE_ACCOUNT_KEY_client_email = ''
process.env.FIREBASE_ACCOUNT_KEY_client_id = ''
process.env.FIREBASE_ACCOUNT_KEY_auth_uri = ''
process.env.FIREBASE_ACCOUNT_KEY_token_uri = ''
process.env.FIREBASE_ACCOUNT_KEY_auth_provider_x509_cert_url = ''
process.env.FIREBASE_ACCOUNT_KEY_client_x509_cert_url = ''

