'use strict'

module.exports = {
    RESPONSE_SUCCESS: 'OK',
    RESPONSE_ERROR_BAD_REQUEST: '400',
    RESPONSE_ERROR_UNAUTHORIZED: '401',
    RESPONSE_ERROR_FORBIDDEN: '403',
    RESPONSE_ERROR_NOT_FOUND: '404',
    RESPONSE_ERROR_INTERNAL: '500',
    AUTH_SCOPE_SERVER: 1,
    AUTH_SCOPE_MOBILE: 2
}