// GET VerifyPhone
POST {{base-url}}/mobile/users/verifyPhone
Content-Type: application/json

{
  "appId": "{{app-id}}",
  "appSecret": "{{app-secret}}",
  "countryCode": "62",
  "phone": "08123456789"
}

###

// GET RegisterUser
POST {{base-url}}/mobile/users/register
Content-Type: application/json

{
  "countryCode": "62",
  "phone": "08123456789",
  "deviceId": "INTELLIJ_HTTP_REST_CLIENT",
  "verificationCode": "6018",
  "appId": "{{app-id}}",
  "appSecret": "{{app-secret}}"
}

###

// GET CheckLogin
GET {{base-url}}/mobile/users/login
  ?appId={{app-id}}
  &appSecret={{app-secret}}
  &hash={{user-hash}}
Content-Type: application/json

###

// GET RevokeAppsAccess
PUT {{base-url}}/mobile/users/revokeAccess
Content-Type: application/json

{
  "appId": "{{app-id}}",
  "appSecret": "{{app-secret}}",
  "userHash": "{{app-hash}}"
}

###